language: php

os:
  - linux

dist: focal

jobs:

    include:
#        - dist: focal
#          php: '5.4'
#        - dist: focal
#          php: '5.5'
#        - dist: focal
#          php: '5.6'
#        - dist: focal
#          php: '7.0'
#        - dist: focal
#          php: '7.1'
#        - dist: focal
#          php: '7.2'
#        - dist: focal
#          php: '7.3'
        - dist: focal
          php: '7.4'
        - dist: focal
          php: '8.0'

#        - dist: bionic
#          php: '5.4'
#        - dist: bionic
#          php: '5.5'
#        - dist: bionic
#          php: '5.6'
        - dist: bionic
          php: '7.0'
        - dist: bionic
          php: '7.1'
        - dist: bionic
          php: '7.2'
        - dist: bionic
          php: '7.3'
        - dist: bionic
          php: '7.4'
        - dist: bionic
          php: '8.0'

#        - dist: xenial
#          php: '5.4'
#        - dist: xenial
#          php: '5.5'
        - dist: xenial
          php: '5.6'
        - dist: xenial
          php: '7.0'
        - dist: xenial
          php: '7.1'
        - dist: xenial
          php: '7.2'
        - dist: xenial
          php: '7.3'
        - dist: xenial
          php: '7.4'
        - dist: xenial
          php: '8.0'

        - dist: trusty
          php: '5.4'
        - dist: trusty
          php: '5.5'
        - dist: trusty
          php: '5.6'
        - dist: trusty
          php: '7.0'
        - dist: trusty
          php: '7.1'
        - dist: trusty
          php: '7.2'
        - dist: trusty
          php: '7.3'
        - dist: trusty
          php: '7.4'
        - dist: trusty
          php: '8.0'

        - dist: precise
          php: '5.4'
        - dist: precise
          php: '5.5'
        - dist: precise
          php: '5.6'
        - dist: precise
          php: '7.0'
        - dist: precise
          php: '7.1'
        - dist: precise
          php: '7.2'
        - dist: precise
          php: '7.3'
#        - dist: precise
#          php: '7.4'
#        - dist: precise
#          php: '8.0'

before_install:
  # If PHP >= 7.0, force use of PHPUnit 5.7
  - if {[version_compare($TRAVIS_PHP_VERSION, '5.4.0') >= 0) && version_compare($TRAVIS_PHP_VERSION, '5.6.0') <= 0)]};"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-4.phar && chmod +x ~/bin/phpunit; fi
  - if {[version_compare($TRAVIS_PHP_VERSION, '5.6.0') >= 0) && version_compare($TRAVIS_PHP_VERSION, '7.0.0') <= 0)]};"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-5.phar && chmod +x ~/bin/phpunit; fi
  - if {[version_compare($TRAVIS_PHP_VERSION, '7.0.0') >= 0) && version_compare($TRAVIS_PHP_VERSION, '7.1.0') <= 0)]};"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-6.phar && chmod +x ~/bin/phpunit; fi
  - if {[version_compare($TRAVIS_PHP_VERSION, '7.1.0') >= 0) && version_compare($TRAVIS_PHP_VERSION, '7.2.0') <= 0)]};"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-7.phar && chmod +x ~/bin/phpunit; fi
  - if {[version_compare($TRAVIS_PHP_VERSION, '7.2.0') >= 0) && version_compare($TRAVIS_PHP_VERSION, '7.3.0') <= 0)]};"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-8.phar && chmod +x ~/bin/phpunit; fi
  - if [version_compare($TRAVIS_PHP_VERSION, '7.3.0') >= 0)];"; then mkdir -p ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-9.phar && chmod +x ~/bin/phpunit; fi

script: 
 phpunit tests

#notifications:
#  irc: "irc.freenode.org#ltb-project"
